server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://sca-orporas-t;databaseName=MTIWeb;encrypt=false;trustServerCertificate=false;
    username: devMTIWeb
    password: lethn34olj
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
